# 1.2.1 Пример

In [ ]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2

In [ ]:
a  = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, '\n', b, '\n', c, '\n', d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


# 1.2.3 Пример

In [ ]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.0038250757441011807 0.9877333522433973 0.45511231041410055


# 1.2.4 Пример

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 1.2.6 Пример

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

In [ ]:
A = np.arange(64).reshape(8,8)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            A[i][j] = 0
        else:
            A[i][j] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2 Задание

In [ ]:
A = np.arange(25).reshape(5,5)
for i in range(5):
    for j in range(5):
        A[i][j] = A[i][j]%5
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание

In [ ]:
Z = np.random.random((3,3,3))
print(Z)


[[[1.75484214e-01 6.74297741e-04 5.47089632e-01]
  [1.58128125e-01 5.18557264e-01 9.49915284e-01]
  [9.09610706e-01 4.16909159e-01 2.02307701e-01]]

 [[6.65377900e-01 6.73288576e-01 3.67450121e-01]
  [3.17371911e-01 6.56032211e-01 3.50848992e-01]
  [9.03073823e-01 4.46929960e-01 4.46962154e-01]]

 [[6.51079280e-01 5.61963307e-01 3.44433538e-01]
  [5.45653719e-01 4.94083817e-01 3.61499044e-01]
  [4.93237200e-01 4.53528401e-02 5.74454418e-01]]]


# 1.3.4 Задание

In [ ]:
A = np.arange(25).reshape(5,5)
for i in range(5):
    for j in range(5):
        if i == 0 or j == 0 or i == 4 or j == 4:
            A[i][j] = 1
        else:
            A[i][j] = 0
print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# 1.3.5 Задание

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr = np.sort(arr)
arr = arr[::-1]
print(arr)

[8 7 6 5 4 3 2 1]


# 1.3.6 Задание

In [ ]:
n = int(input())
m = int(input())
A = np.arange(n*m).reshape(n,m)
print (np.shape(A))
print(A.ndim)
print(np.size(A))


2
2
(2, 2)
2
4


# 2.2.1 Пример

In [ ]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


# 2.2.2 Пример

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2= pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# 2.2.3 Пример

In [ ]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ["Джеки Джексон", "Стивен Стивенсон"]
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

In [ ]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример

In [ ]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 2.2.6 Пример

In [ ]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

In [ ]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

In [ ]:
a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])
sum((a - b)**2)**.5

2.0

# 2.3.2 Задание

In [ ]:
url1 = 'https://raw.githubusercontent.com/akmand/datasets/main/airline_passenger_satisfaction.csv'
dataframe1 = pd.read_csv(url1)
dataframe1.head(5)

Gender      customer_type  age   type_of_travel customer_class  \
0    Male     Loyal Customer   13  Personal Travel       Eco Plus   
1    Male  disloyal Customer   25  Business travel       Business   
2  Female     Loyal Customer   26  Business travel       Business   
3  Female     Loyal Customer   25  Business travel       Business   
4    Male     Loyal Customer   61  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
0              460                      3                                  4   
1              235                      3                                  2   
2             1142                      2                                  2   
3              562                      2                                  5   
4              214                      3                                  3   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
0                       3              1  ...                       5   
1                       3              3  ...                       1   
2                       2              2  ...                       5   
3                       5              5  ...                       2   
4                       3              3  ...                       3   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
0                4                 3                 4                4   
1                1                 5                 3                1   
2                4                 3                 4                4   
3                2                 5                 3                1   
4                3                 4                 4                3   

   inflight_service  cleanliness  departure_delay_in_minutes  \
0                 5            5                          25   
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   
4                 3            3                           0   

   arrival_delay_in_minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  
4                       0.0                satisfied  

[5 rows x 23 columns]

# 2.3.3 Задание

In [ ]:
dataframe1.head(2)

age  flight_distance  inflight_wifi_service  \
count  129880.000000    129880.000000          129880.000000   
mean       39.427957      1190.316392               2.728696   
std        15.119360       997.452477               1.329340   
min         7.000000        31.000000               0.000000   
25%        27.000000       414.000000               2.000000   
50%        40.000000       844.000000               3.000000   
75%        51.000000      1744.000000               4.000000   
max        85.000000      4983.000000               5.000000   

       departure_arrival_time_convenient  ease_of_online_booking  \
count                      129880.000000           129880.000000   
mean                            3.057599                2.756876   
std                             1.526741                1.401740   
min                             0.000000                0.000000   
25%                             2.000000                2.000000   
50%                             3.000000                3.000000   
75%                             4.000000                4.000000   
max                             5.000000                5.000000   

       gate_location  food_and_drink  online_boarding   seat_comfort  \
count  129880.000000   129880.000000    129880.000000  129880.000000   
mean        2.976925        3.204774         3.252633       3.441361   
std         1.278520        1.329933         1.350719       1.319289   
min         0.000000        0.000000         0.000000       0.000000   
25%         2.000000        2.000000         2.000000       2.000000   
50%         3.000000        3.000000         3.000000       4.000000   
75%         4.000000        4.000000         4.000000       5.000000   
max         5.000000        5.000000         5.000000       5.000000   

       inflight_entertainment  onboard_service  leg_room_service  \
count           129880.000000    129880.000000     129880.000000   
mean                 3.358077         3.383023          3.350878   
std                  1.334049         1.287099          1.316252   
min                  0.000000         0.000000          0.000000   
25%                  2.000000         2.000000          2.000000   
50%                  4.000000         4.000000          4.000000   
75%                  4.000000         4.000000          4.000000   
max                  5.000000         5.000000          5.000000   

       baggage_handling  checkin_service  inflight_service    cleanliness  \
count     129880.000000    129880.000000     129880.000000  129880.000000   
mean           3.632114         3.306267          3.642193       3.286326   
std            1.180025         1.266185          1.176669       1.313682   
min            1.000000         0.000000          0.000000       0.000000   
25%            3.000000         3.000000          3.000000       2.000000   
50%            4.000000         3.000000          4.000000       3.000000   
75%            5.000000         4.000000          5.000000       4.000000   
max            5.000000         5.000000          5.000000       5.000000   

       departure_delay_in_minutes  arrival_delay_in_minutes  
count               129880.000000             129487.000000  
mean                    14.713713                 15.091129  
std                     38.071126                 38.465650  
min                      0.000000                  0.000000  
25%                      0.000000                  0.000000  
50%                      0.000000                  0.000000  
75%                     12.000000                 13.000000  
max                   1592.000000               1584.000000

In [ ]:
dataframe1.tail(3)

Gender   customer_type  age   type_of_travel customer_class  \
129877  Female  Loyal Customer   17  Personal Travel            Eco   
129878    Male  Loyal Customer   14  Business travel       Business   
129879  Female  Loyal Customer   42  Personal Travel            Eco   

        flight_distance  inflight_wifi_service  \
129877              828                      2   
129878             1127                      3   
129879              264                      2   

        departure_arrival_time_convenient  ease_of_online_booking  \
129877                                  5                       1   
129878                                  3                       3   
129879                                  5                       2   

        gate_location  ...  inflight_entertainment  onboard_service  \
129877              5  ...                       2                4   
129878              3  ...                       4                3   
129879              5  ...                       1                1   

        leg_room_service  baggage_handling  checkin_service  inflight_service  \
129877                 3                 4                5                 4   
129878                 2                 5                4                 5   
129879                 2                 1                1                 1   

        cleanliness  departure_delay_in_minutes  arrival_delay_in_minutes  \
129877            2                           0                       0.0   
129878            4                           0                       0.0   
129879            1                           0                       0.0   

                   satisfaction  
129877  neutral or dissatisfied  
129878                satisfied  
129879  neutral or dissatisfied  

[3 rows x 23 columns]

In [ ]:
dataframe1.shape

(129880, 23)

In [ ]:
dataframe1.describe()

age  flight_distance  inflight_wifi_service  \
count  129880.000000    129880.000000          129880.000000   
mean       39.427957      1190.316392               2.728696   
std        15.119360       997.452477               1.329340   
min         7.000000        31.000000               0.000000   
25%        27.000000       414.000000               2.000000   
50%        40.000000       844.000000               3.000000   
75%        51.000000      1744.000000               4.000000   
max        85.000000      4983.000000               5.000000   

       departure_arrival_time_convenient  ease_of_online_booking  \
count                      129880.000000           129880.000000   
mean                            3.057599                2.756876   
std                             1.526741                1.401740   
min                             0.000000                0.000000   
25%                             2.000000                2.000000   
50%                             3.000000                3.000000   
75%                             4.000000                4.000000   
max                             5.000000                5.000000   

       gate_location  food_and_drink  online_boarding   seat_comfort  \
count  129880.000000   129880.000000    129880.000000  129880.000000   
mean        2.976925        3.204774         3.252633       3.441361   
std         1.278520        1.329933         1.350719       1.319289   
min         0.000000        0.000000         0.000000       0.000000   
25%         2.000000        2.000000         2.000000       2.000000   
50%         3.000000        3.000000         3.000000       4.000000   
75%         4.000000        4.000000         4.000000       5.000000   
max         5.000000        5.000000         5.000000       5.000000   

       inflight_entertainment  onboard_service  leg_room_service  \
count           129880.000000    129880.000000     129880.000000   
mean                 3.358077         3.383023          3.350878   
std                  1.334049         1.287099          1.316252   
min                  0.000000         0.000000          0.000000   
25%                  2.000000         2.000000          2.000000   
50%                  4.000000         4.000000          4.000000   
75%                  4.000000         4.000000          4.000000   
max                  5.000000         5.000000          5.000000   

       baggage_handling  checkin_service  inflight_service    cleanliness  \
count     129880.000000    129880.000000     129880.000000  129880.000000   
mean           3.632114         3.306267          3.642193       3.286326   
std            1.180025         1.266185          1.176669       1.313682   
min            1.000000         0.000000          0.000000       0.000000   
25%            3.000000         3.000000          3.000000       2.000000   
50%            4.000000         3.000000          4.000000       3.000000   
75%            5.000000         4.000000          5.000000       4.000000   
max            5.000000         5.000000          5.000000       5.000000   

       departure_delay_in_minutes  arrival_delay_in_minutes  
count               129880.000000             129487.000000  
mean                    14.713713                 15.091129  
std                     38.071126                 38.465650  
min                      0.000000                  0.000000  
25%                      0.000000                  0.000000  
50%                      0.000000                  0.000000  
75%                     12.000000                 13.000000  
max                   1592.000000               1584.000000

In [ ]:
dataframe1.iloc[1:4]

Gender      customer_type  age   type_of_travel customer_class  \
1    Male  disloyal Customer   25  Business travel       Business   
2  Female     Loyal Customer   26  Business travel       Business   
3  Female     Loyal Customer   25  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
1              235                      3                                  2   
2             1142                      2                                  2   
3              562                      2                                  5   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
1                       3              3  ...                       1   
2                       2              2  ...                       5   
3                       5              5  ...                       2   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
1                1                 5                 3                1   
2                4                 3                 4                4   
3                2                 5                 3                1   

   inflight_service  cleanliness  departure_delay_in_minutes  \
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   

   arrival_delay_in_minutes             satisfaction  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  

[3 rows x 23 columns]

In [ ]:
dataframe1[dataframe1['customer_class'] == 'Business'].head(2)

Gender      customer_type  age   type_of_travel customer_class  \
1    Male  disloyal Customer   25  Business travel       Business   
2  Female     Loyal Customer   26  Business travel       Business   

   flight_distance  inflight_wifi_service  departure_arrival_time_convenient  \
1              235                      3                                  2   
2             1142                      2                                  2   

   ease_of_online_booking  gate_location  ...  inflight_entertainment  \
1                       3              3  ...                       1   
2                       2              2  ...                       5   

   onboard_service  leg_room_service  baggage_handling  checkin_service  \
1                1                 5                 3                1   
2                4                 3                 4                4   

   inflight_service  cleanliness  departure_delay_in_minutes  \
1                 4            1                           1   
2                 4            5                           0   

   arrival_delay_in_minutes             satisfaction  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  

[2 rows x 23 columns]

#3.2.1 Пример

In [ ]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

#3.2.2 Пример

In [ ]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized
print("Среднее:", round (standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


#3.2.3 Пример


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

#3.3.2 Задание

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import zscore
url2 = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url2)
scaler1 = MinMaxScaler()
scaler2 = StandardScaler()

df[['sepal_length_cm']] = scaler1.fit_transform(df[["sepal_length_cm"]])
df


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222             3.5              1.4             0.2   
1           0.166667             3.0              1.4             0.2   
2           0.111111             3.2              1.3             0.2   
3           0.083333             3.1              1.5             0.2   
4           0.194444             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667             3.0              5.2             2.3   
146         0.555556             2.5              5.0             1.9   
147         0.611111             3.0              5.2             2.0   
148         0.527778             3.4              5.4             2.3   
149         0.444444             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [ ]:
df[['sepal_length_cm']] = scaler2.fit_transform(df[["sepal_length_cm"]])
df

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0          -0.900681             3.5              1.4             0.2   
1          -1.143017             3.0              1.4             0.2   
2          -1.385353             3.2              1.3             0.2   
3          -1.506521             3.1              1.5             0.2   
4          -1.021849             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145         1.038005             3.0              5.2             2.3   
146         0.553333             2.5              5.0             1.9   
147         0.795669             3.0              5.2             2.0   
148         0.432165             3.4              5.4             2.3   
149         0.068662             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]